[package]
name = "send_bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"

[[bin]]
name = "rand_gen"
path = "src/rand_gen.rs"
[[bin]]
name = "rock_paper"
path = "src/rock_paper.rs"
[[bin]]
name = "pony_powers"
path = "src/pony_powers.rs"